---
abstract: unknown
author:
  - 'Jesse Vincent (jesse@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.131560'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-Hours
no_index:
  directory:
    - t
    - inc
requires:
  Set::IntSpan: 1.12
  Time::Local: 0
version: 0.12
